# permissions for end users to edit containerinjectors.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: containerinjector-editor-role
rules:
- apiGroups:
  - apple.dev.thenullchannel
  resources:
  - containerinjectors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apple.dev.thenullchannel
  resources:
  - containerinjectors/status
  verbs:
  - get
